/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import React, { useRef, useState } from 'react'
import { useFrame, useThree } from 'react-three-fiber'
import * as THREE from 'three'
import { Vector3, Euler } from 'three'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import MeshCollider from './three/MeshCollider'


type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
    SpawnRoom: THREE.Mesh
    Cube001: THREE.Mesh
    Cube002: THREE.Mesh
    Cube003: THREE.Mesh
    Cube004: THREE.Mesh
    RoomWalls001: THREE.Mesh
    Cube005: THREE.Mesh
    Corner: THREE.Mesh
    Cube006: THREE.Mesh
    Mouse_Mouse_0: THREE.Mesh
    Corner001: THREE.Mesh
    Cube013: THREE.Mesh
    Cube012: THREE.Mesh
    Cube011: THREE.Mesh
    Cube010: THREE.Mesh
    Cube009: THREE.Mesh
    Cube008: THREE.Mesh
    Cube007: THREE.Mesh
    RoomWalls: THREE.Mesh
    Straight001: THREE.Mesh
    Cube014: THREE.Mesh
    Straight002: THREE.Mesh
    Cube015: THREE.Mesh
    Straight003: THREE.Mesh
    Cube016: THREE.Mesh
    Straight004: THREE.Mesh
    Cube017: THREE.Mesh
    Straight005: THREE.Mesh
    Cube018: THREE.Mesh
    Straight006: THREE.Mesh
    Cube019: THREE.Mesh
    Straight007: THREE.Mesh
    Corner002: THREE.Mesh
    Cube021: THREE.Mesh
    Cube020: THREE.Mesh
    Corner003: THREE.Mesh
    Cube023: THREE.Mesh
    Cube022: THREE.Mesh
    Corner004: THREE.Mesh
    Cube024: THREE.Mesh
    Cube025: THREE.Mesh
    Corner005: THREE.Mesh
    Cube027: THREE.Mesh
    Cube026: THREE.Mesh
    Cube028: THREE.Mesh
    Straight008: THREE.Mesh
    Cube029: THREE.Mesh
    Straight009: THREE.Mesh
    Cube030: THREE.Mesh
    Straight010: THREE.Mesh
    Cube034: THREE.Mesh
    Cube033: THREE.Mesh
    Cube032: THREE.Mesh
    Cube031: THREE.Mesh
    Straight014: THREE.Mesh
    Straight013: THREE.Mesh
    Straight012: THREE.Mesh
    Straight011: THREE.Mesh
    Cube035: THREE.Mesh
    Straight015: THREE.Mesh
    Corner006: THREE.Mesh
    Cube037: THREE.Mesh
    Cube036: THREE.Mesh
    Corner007: THREE.Mesh
    Cube039: THREE.Mesh
    Cube038: THREE.Mesh
    Cube044: THREE.Mesh
    Cube043: THREE.Mesh
    Cube042: THREE.Mesh
    Cube041: THREE.Mesh
    Cube040: THREE.Mesh
    Straight016: THREE.Mesh
    Cube046: THREE.Mesh
    Straight017: THREE.Mesh
    Cube047: THREE.Mesh
    Cube045: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshPhongMaterial
    Mouse: THREE.MeshPhongMaterial
  }
}

export default function EarlyGame(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('models/early-game.glb') as GLTFResult

  let parentPosition = new Vector3()
  let parentRotation = new Euler()
  if (props.position instanceof Array) parentPosition.set(...(props.position as [number, number, number]))
  if (props.rotation instanceof Array) parentRotation.set(...(props.rotation as [number, number, number]))
  if (props.position instanceof Vector3) parentPosition.copy(props.position)
  if (props.rotation instanceof Euler) parentRotation.copy(props.rotation)

  const parentTransform = { parentPosition, parentRotation }

  const algernonPos = new Vector3(2, 0, 0)
  const [algergone, setAlgergone] = useState(false)
  const { camera } = useThree()
  useFrame(() => {
    if (algergone) return
    if (camera.position.clone().sub(algernonPos).length() <= 4.5) setAlgergone(true)
  })

  return (
    <group ref={group} dispose={null}>
      {!algergone && <group>
        <spotLight
          position={[-2, 0, 0.1]}
          angle={Math.PI/16}
          castShadow
          color="red"
        />
        <MeshCollider {...parentTransform} material={materials.Mouse}    geometry={nodes.Mouse_Mouse_0.geometry}/>
      </group>}

      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.SpawnRoom.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube001.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube002.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube003.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube004.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.RoomWalls001.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube005.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Corner.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube006.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Corner001.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube013.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube012.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube011.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube010.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube009.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube008.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube007.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.RoomWalls.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Straight001.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube014.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Straight002.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube015.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Straight003.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube016.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Straight004.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube017.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Straight005.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube018.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Straight006.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube019.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Straight007.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Corner002.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube021.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube020.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Corner003.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube023.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube022.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Corner004.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube024.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube025.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Corner005.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube027.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube026.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube028.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Straight008.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube029.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Straight009.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube030.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Straight010.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube034.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube033.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube032.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube031.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Straight014.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Straight013.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Straight012.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Straight011.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube035.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Straight015.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Corner006.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube037.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube036.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Corner007.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube039.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube038.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube044.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube043.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube042.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube041.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube040.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Straight016.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube046.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Straight017.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube047.geometry} />
      <MeshCollider {...parentTransform} material={materials.Material} geometry={nodes.Cube045.geometry} />
    </group>
  )
}

useGLTF.preload('models/early-game.glb')
