/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Text, useGLTF } from '@react-three/drei'
import React, { useEffect, useRef, useState } from 'react'
import { useFrame, useThree } from 'react-three-fiber'
import * as THREE from 'three'
import { Clock, Vector3 } from 'three'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import Cheese from './early-game/Cheese'
import Whiteboard from './early-game/Whiteboard'
import Whiteboard2 from './early-game/Whiteboard2'
import MeshCollider from './three/MeshCollider'

type GLTFResult = GLTF & {
  nodes: any,
  materials: {
    Material: THREE.MeshPhongMaterial
    Mouse: THREE.MeshPhongMaterial
  }
}

export default function EarlyGame(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('models/early-game.glb') as GLTFResult
  const { camera } = useThree()

  const algernonPos = new Vector3(2, 0, 0)
  const [algergone, setAlgergone] = useState(false)
  const updateAlgernon = () => {
    if (algergone) return
    if (camera.position.clone().sub(algernonPos).length() <= 5) {
      setAlgergone(true)
      squeaks.forEach(squeak => squeak.pause())
    }
  }

  const squeaks = [
    new Audio('sounds/squeak-1.mp3'),
    new Audio('sounds/squeak-2.mp3'),
    new Audio('sounds/squeak-3.mp3'),
    new Audio('sounds/squeak-4.mp3'),
    new Audio('sounds/squeak-5.mp3'),
    new Audio('sounds/squeak-6.mp3'),
  ]
  const playSqueak = () => {
    if (algergone) return
    const randomSqueak = squeaks[Math.floor(Math.random() * squeaks.length)]
    randomSqueak.currentTime = 0
    randomSqueak.play()
  }
  playSqueak()

  const [stage1Complete, setStage1Complete] = useState(false)
  const whiteboardPos = new Vector3(34.5, 21.5, 0)
  const updateStage1 = () => {
    if (stage1Complete) return
    if (camera.position.clone().sub(whiteboardPos).length() <= 10) {
      setStage1Complete(true)
      new Audio('sounds/applause.wav').play()
      new Audio('sounds/party-horn.wav').play()
    }
  }

  const [cheeseAcquired, setCheeseAcquired] = useState(false)
  const cheesePos = new Vector3(39, 20, 0.5)
  const updateCheese = () => {
    if (cheeseAcquired) return
    if (camera.position.clone().sub(cheesePos).length() <= 0.5) {
      setCheeseAcquired(true)
      new Audio('sounds/munch.wav').play()
    }
  }

  const [stage2Complete, setStage2Complete] = useState(false)
  const whiteboard2Pos = new Vector3(65, 47, 0)
  const updateStage2 = () => {
    if (stage2Complete) return
    if (camera.position.clone().sub(whiteboard2Pos).length() <= 10) {
      setStage2Complete(true)
      new Audio('sounds/applause.wav').play()
      new Audio('sounds/party-horn.wav').play()
    }
  }

  const [cheese2Acquired, setCheese2Acquired] = useState(false)
  const cheese2Pos = new Vector3(64, 51, 0.5)
  const updateCheese2 = () => {
    if (cheese2Acquired) return
    if (camera.position.clone().sub(cheese2Pos).length() <= 0.5) {
      setCheese2Acquired(true)
      new Audio('sounds/munch.wav').play()
    }
  }

  useFrame(() => {
    updateAlgernon()
    updateStage1()
    updateCheese()
    updateStage2()
    updateCheese2()
  })

  return (
    <group ref={group} dispose={null}>
      <group visible={!algergone}>
        <spotLight
          position={[-2, 0, 0.1]}
          angle={Math.PI/16}
          castShadow
          color="red"
        />
        <mesh material={materials.Mouse} geometry={nodes.Mouse_Mouse_0.geometry} position={[2.05, 0, 0.16]} castShadow receiveShadow/>
      </group>

      <Text
        color="black"
        position={[11.999, 20, 1]}
        rotation={[Math.PI/2, -Math.PI/2, 0]}
        fontSize={.5}
        fillOpacity={.15}
      > {`<  ?  >`} </Text>

      <Text
        color="black"
        position={[30, 26.001, 1]}
        rotation={[Math.PI/2, 0, 0]}
        fontSize={.5}
        fillOpacity={.15}
      > :( </Text>

      {/* <Text
        color="black"
        position={[30.999, 12, 1]}
        rotation={[Math.PI/2, -Math.PI/2, 0]}
        fontSize={.5}
        fillOpacity={.15}
      > :) </Text> */}

      <Whiteboard position={whiteboardPos} rotation={[0, 0, -3 * Math.PI/4]}/>
      <Cheese position={cheesePos} visible={!cheeseAcquired} scale={[0.2, 0.2, 0.2]}/>

      <Text
        color="black"
        position={[39.25, 20, 0.01]}
        rotation={[0, 0, -Math.PI/2]}
        fontSize={.5}
        fillOpacity={.15}
      >onward</Text>

      <Whiteboard2 position={whiteboard2Pos} rotation={[0, 0, Math.PI]}/>
      <Cheese position={cheese2Pos} visible={!cheese2Acquired} scale={[0.2, 0.2, 0.2]}/>

      <Text
        color="black"
        position={[64, 52.25, 0.01]}
        rotation={[0, 0, 0]}
        fontSize={.5}
        fillOpacity={.15}
      >again</Text>

      <MeshCollider material={materials.Material} geometry={nodes.Cube.geometry} position={[0, 1.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.SpawnRoom.geometry} position={[0, -1.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube001.geometry} position={[1.5, 4, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube002.geometry} position={[1.5, -4, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube003.geometry} position={[7, 5.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube004.geometry} position={[7, -5.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.RoomWalls001.geometry} position={[12.5, 0, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube005.geometry} position={[-5.5, 0, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Corner.geometry} position={[-4, -1.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube006.geometry} position={[-2.5, 1.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Corner001.geometry} position={[-4, 21.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube013.geometry} position={[0, 18.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube012.geometry} position={[1.5, 16, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube011.geometry} position={[1.5, 24, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube010.geometry} position={[7, 14.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube009.geometry} position={[7, 25.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube008.geometry} position={[-5.5, 20, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube007.geometry} position={[-2.5, 18.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.RoomWalls.geometry} position={[12.5, 20, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Straight001.geometry} position={[0, 21.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube014.geometry} position={[-2.5, 4, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Straight002.geometry} position={[-5.5, 4, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube015.geometry} position={[-2.5, 8, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Straight003.geometry} position={[-5.5, 8, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube016.geometry} position={[-2.5, 12, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Straight004.geometry} position={[-5.5, 12, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube017.geometry} position={[-2.5, 16, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Straight005.geometry} position={[-5.5, 16, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube018.geometry} position={[14, 14.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Straight006.geometry} position={[14, 17.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube019.geometry} position={[14, 22.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Straight007.geometry} position={[14, 25.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Corner002.geometry} position={[19.5, 24, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube021.geometry} position={[16.5, 25.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube020.geometry} position={[18, 22.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Corner003.geometry} position={[18, 17.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube023.geometry} position={[19.5, 16, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube022.geometry} position={[16.5, 14.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Corner004.geometry} position={[47, 21.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube024.geometry} position={[45.5, 23, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube025.geometry} position={[48.5, 23, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Corner005.geometry} position={[16.5, 28, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube027.geometry} position={[18, 29.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube026.geometry} position={[19.5, 26.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube028.geometry} position={[22, 10.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Straight008.geometry} position={[22, 13.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube029.geometry} position={[22, 26.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Straight009.geometry} position={[22, 29.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube030.geometry} position={[26, 26.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Straight010.geometry} position={[26, 29.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Straight014.geometry} position={[28.5, 16, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Straight013.geometry} position={[28.5, 20, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Straight012.geometry} position={[28.5, 24, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube035.geometry} position={[26, 10.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Straight015.geometry} position={[26, 13.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Corner006.geometry} position={[18, 10.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube037.geometry} position={[19.5, 13.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube036.geometry} position={[16.5, 12, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Corner007.geometry} position={[31.5, 12, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube039.geometry} position={[30, 10.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube038.geometry} position={[28.5, 13.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube044.geometry} position={[35, 25.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube043.geometry} position={[35, 14.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube042.geometry} position={[28.5, 24, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube041.geometry} position={[28.5, 16, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube046.geometry} position={[41, 18.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Straight017.geometry} position={[41, 21.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube047.geometry} position={[39.5, 16, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube045.geometry} position={[39.5, 24, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Corner008.geometry} position={[31.5, 12, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube033.geometry} position={[28.5, 13.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube032.geometry} position={[30, 10.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Corner009.geometry} position={[31.5, 28, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube034.geometry} position={[28.5, 26.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube031.geometry} position={[30, 29.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.ExitBlocked.geometry} position={[30, 25.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube040.geometry} position={[42.5, 23, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Corner010.geometry} position={[42.5, 27, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube049.geometry} position={[44, 28.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube048.geometry} position={[45.5, 25.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Corner011.geometry} position={[48.5, 27, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube051.geometry} position={[45.5, 25.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube050.geometry} position={[47, 28.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube052.geometry} position={[45, 18.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube053.geometry} position={[50, 24.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Corner012.geometry} position={[49, 18.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube054.geometry} position={[51.5, 20, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Corner013.geometry} position={[48.5, 29, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube055.geometry} position={[50, 30.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Corner014.geometry} position={[51.5, 29, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Corner015.geometry} position={[52, 18.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube056.geometry} position={[54.5, 26, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube057.geometry} position={[53, 27.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube058.geometry} position={[54.5, 23, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube059.geometry} position={[57.5, 21, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Corner016.geometry} position={[56, 18.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube060.geometry} position={[56, 30.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube061.geometry} position={[57.5, 28, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube062.geometry} position={[57.5, 25, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube063.geometry} position={[57.5, 33, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube064.geometry} position={[57.5, 35, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube065.geometry} position={[53, 33.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube066.geometry} position={[54.5, 35, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube067.geometry} position={[56, 36.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Corner017.geometry} position={[48.5, 35, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube068.geometry} position={[50, 36.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube069.geometry} position={[51.5, 38, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube070.geometry} position={[53, 39.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube071.geometry} position={[54.5, 38, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube072.geometry} position={[47, 33.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.ExitBlocked001.geometry} position={[45.5, 32, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Corner018.geometry} position={[42.5, 31, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Corner019.geometry} position={[42.5, 35, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube073.geometry} position={[51.5, 41, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube074.geometry} position={[47, 39.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube075.geometry} position={[50, 42.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube076.geometry} position={[45.5, 41, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube077.geometry} position={[51.5, 41, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube078.geometry} position={[47, 42.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Corner020.geometry} position={[42.5, 39, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Corner021.geometry} position={[42.5, 43, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube079.geometry} position={[45.5, 44, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Corner022.geometry} position={[42.5, 46, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube080.geometry} position={[44, 48.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube081.geometry} position={[48.5, 47, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube082.geometry} position={[47, 48.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube083.geometry} position={[50, 45.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube084.geometry} position={[50, 48.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube085.geometry} position={[53, 48.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube086.geometry} position={[54.5, 44, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube087.geometry} position={[54.5, 47, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube088.geometry} position={[57.5, 39, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube089.geometry} position={[57.5, 43, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube090.geometry} position={[57.5, 44, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube092.geometry} position={[56, 48.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube093.geometry} position={[57.5, 51, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube094.geometry} position={[57.5, 43, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube095.geometry} position={[69.5, 47, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube096.geometry} position={[63, 41.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube091.geometry} position={[68, 52.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube097.geometry} position={[60, 52.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube098.geometry} position={[65.5, 54, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube099.geometry} position={[62.5, 54, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube102.geometry} position={[64, 58.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube103.geometry} position={[62.5, 57, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube104.geometry} position={[79, 58.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube105.geometry} position={[79, 55.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube100.geometry} position={[75, 58.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube101.geometry} position={[75, 55.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube106.geometry} position={[71, 58.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube107.geometry} position={[71, 55.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube108.geometry} position={[67, 58.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube109.geometry} position={[67, 55.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube110.geometry} position={[83, 58.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube111.geometry} position={[83, 55.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube120.geometry} position={[83, 54.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube121.geometry} position={[83, 51.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube112.geometry} position={[83, 62.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube113.geometry} position={[83, 59.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube114.geometry} position={[86.5, 48, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube115.geometry} position={[89.5, 48, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube117.geometry} position={[85.5, 49.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube119.geometry} position={[90.5, 48, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube122.geometry} position={[93.5, 48, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube123.geometry} position={[94.5, 48, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube124.geometry} position={[97.5, 48, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube126.geometry} position={[98.5, 49.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube128.geometry} position={[101, 58.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube129.geometry} position={[101, 55.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube130.geometry} position={[101, 54.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube131.geometry} position={[101, 51.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube132.geometry} position={[101, 62.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube133.geometry} position={[101, 59.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube134.geometry} position={[84.5, 64.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube135.geometry} position={[84.5, 63.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube136.geometry} position={[85.5, 64.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube138.geometry} position={[98.5, 64.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube140.geometry} position={[86.5, 66, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube141.geometry} position={[89.5, 66, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube142.geometry} position={[90.5, 66, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube143.geometry} position={[93.5, 66, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube144.geometry} position={[94.5, 66, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube145.geometry} position={[97.5, 66, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube146.geometry} position={[83, 47.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube147.geometry} position={[89.5, 48, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube148.geometry} position={[77.5, 53, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube149.geometry} position={[79, 54.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube150.geometry} position={[77.5, 49, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube151.geometry} position={[79, 47.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube152.geometry} position={[80.5, 51.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube153.geometry} position={[80.5, 50.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube154.geometry} position={[84.5, 49, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube155.geometry} position={[83, 50.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube156.geometry} position={[79, 59.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube157.geometry} position={[77.5, 61, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube158.geometry} position={[80.5, 63.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube159.geometry} position={[83, 63.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube160.geometry} position={[80.5, 62.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube161.geometry} position={[77.5, 65, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube162.geometry} position={[79, 66.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube163.geometry} position={[83, 66.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube116.geometry} position={[84.5, 65, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube164.geometry} position={[86.5, 45.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube118.geometry} position={[89.5, 44, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube165.geometry} position={[88, 42.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube167.geometry} position={[84, 42.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube168.geometry} position={[82.5, 44, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube169.geometry} position={[84, 45.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube166.geometry} position={[90.5, 44, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube170.geometry} position={[93.5, 44, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube171.geometry} position={[90.5, 40, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube172.geometry} position={[93.5, 40, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube174.geometry} position={[94.5, 44, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube175.geometry} position={[96, 42.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube176.geometry} position={[97.5, 45.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube177.geometry} position={[100, 45.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube178.geometry} position={[100, 42.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube179.geometry} position={[101.5, 44, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube180.geometry} position={[96, 37.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube173.geometry} position={[90.5, 36, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube183.geometry} position={[92, 34.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube184.geometry} position={[93.5, 37.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube186.geometry} position={[96, 34.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube188.geometry} position={[101, 50.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube189.geometry} position={[103.5, 51.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube190.geometry} position={[103.5, 50.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube191.geometry} position={[105, 54.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube192.geometry} position={[106.5, 53, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube193.geometry} position={[106.5, 49, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube194.geometry} position={[105, 47.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube195.geometry} position={[101, 47.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube196.geometry} position={[99.5, 49, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube125.geometry} position={[105, 59.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube127.geometry} position={[106.5, 65, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube197.geometry} position={[106.5, 61, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube198.geometry} position={[103.5, 63.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube199.geometry} position={[103.5, 62.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube200.geometry} position={[101, 63.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube201.geometry} position={[105, 66.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube202.geometry} position={[101, 66.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube203.geometry} position={[99.5, 65, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube137.geometry} position={[105, 58.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube139.geometry} position={[105, 55.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube204.geometry} position={[109, 58.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube205.geometry} position={[109, 55.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube206.geometry} position={[113, 55.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube207.geometry} position={[114.5, 57, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube208.geometry} position={[111.5, 58.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube209.geometry} position={[111.5, 61, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube211.geometry} position={[113, 62.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube210.geometry} position={[114.5, 59.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube212.geometry} position={[117, 62.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube213.geometry} position={[117, 59.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube214.geometry} position={[118.5, 61, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube215.geometry} position={[94.5, 70, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube216.geometry} position={[96, 71.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube217.geometry} position={[100, 71.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube218.geometry} position={[97.5, 68.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube219.geometry} position={[100, 68.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube220.geometry} position={[101.5, 70, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube221.geometry} position={[90.5, 70, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube222.geometry} position={[93.5, 70, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube223.geometry} position={[90.5, 74, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube224.geometry} position={[93.5, 74, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube225.geometry} position={[90.5, 78, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube226.geometry} position={[92, 79.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube227.geometry} position={[93.5, 76.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube228.geometry} position={[96, 76.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube229.geometry} position={[97.5, 78, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube230.geometry} position={[94.5, 79.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube231.geometry} position={[94.5, 82, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube232.geometry} position={[96, 83.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube233.geometry} position={[97.5, 80.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube234.geometry} position={[100, 80.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube235.geometry} position={[100, 83.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube236.geometry} position={[101.5, 82, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube237.geometry} position={[89.5, 70, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube238.geometry} position={[88, 71.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube239.geometry} position={[86.5, 68.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube240.geometry} position={[84, 71.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube241.geometry} position={[84, 68.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube242.geometry} position={[82.5, 70, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube181.geometry} position={[100, 37.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube185.geometry} position={[101.5, 36, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube182.geometry} position={[98.5, 34.5, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube187.geometry} position={[101.5, 32, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube243.geometry} position={[98.5, 32, 1]} />
      <MeshCollider material={materials.Material} geometry={nodes.Cube244.geometry} position={[100, 30.5, 1]} />
    </group>
  )
}

useGLTF.preload('models/early-game.glb')
