/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import React, { useRef } from 'react'
import * as THREE from 'three'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import MeshCollider from '../three/MeshCollider'

type GLTFResult = GLTF & {
  nodes: any,
  materials: {
    Material: THREE.MeshPhongMaterial
  }
}

export default function EarlyGame(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('models/flower-room.glb') as GLTFResult

  return (
    <group ref={group} dispose={null}>
      <MeshCollider geometry={nodes.Cube001.geometry} material={materials.Material} position={[0, 0, 0.2]} />
      <MeshCollider geometry={nodes.Cube002.geometry} material={materials.Material} position={[-1, -1, 0.1]} />
      <MeshCollider geometry={nodes.Cube003.geometry} material={materials.Material} position={[1, 1, 0.1]} />
      <MeshCollider geometry={nodes.Cube004.geometry} material={materials.Material} position={[2, -2, 0.3]} />
      <MeshCollider geometry={nodes.Cube005.geometry} material={materials.Material} position={[-2, 2, 0.3]} />
      <MeshCollider geometry={nodes.Cube006.geometry} material={materials.Material} position={[0, 0, 0.4]} />
      <MeshCollider geometry={nodes.Cube007.geometry} material={materials.Material} position={[4, -4, 0.2]} />
      <MeshCollider geometry={nodes.Cube008.geometry} material={materials.Material} position={[-4, 4, 0.2]} />
      <MeshCollider geometry={nodes.Cube009.geometry} material={materials.Material} position={[3, 3, 0.2]} />
      <MeshCollider geometry={nodes.Cube010.geometry} material={materials.Material} position={[-3, -3, 0.2]} />
      <MeshCollider geometry={nodes.Cube011.geometry} material={materials.Material} position={[0, 0, 0.5]} />
      <MeshCollider geometry={nodes.Cube012.geometry} material={materials.Material} position={[-1.5, -1.5, 0.4]} />
      <MeshCollider geometry={nodes.Cube013.geometry} material={materials.Material} position={[1.5, 1.5, 0.4]} />
      <MeshCollider geometry={nodes.Cube014.geometry} material={materials.Material} position={[5, 5, 0.1]} />
      <MeshCollider geometry={nodes.Cube015.geometry} material={materials.Material} position={[5, -5, 0.1]} />
      <MeshCollider geometry={nodes.Cube016.geometry} material={materials.Material} position={[-5, -5, 0.1]} />
      <MeshCollider geometry={nodes.Cube017.geometry} material={materials.Material} position={[-5, 5, 0.1]} />
      <MeshCollider geometry={nodes.Cube018.geometry} material={materials.Material} position={[27, 1.5, 1]} />
      <MeshCollider geometry={nodes.Cube024.geometry} material={materials.Material} position={[27, -1.5, 1]} />
      <MeshCollider geometry={nodes.Cube022.geometry} material={materials.Material} position={[3.66, 12.29, 1]} />
      <MeshCollider geometry={nodes.Cube019.geometry} material={materials.Material} position={[31, -1.5, 1]} />
      <MeshCollider geometry={nodes.Cube020.geometry} material={materials.Material} position={[29.5, 1.5, 1]} />
      <MeshCollider geometry={nodes.Cube021.geometry} material={materials.Material} position={[32.5, 0, 1]} />
      <MeshCollider geometry={nodes.Cube023.geometry} material={materials.Material} position={[29.5, 4, 1]} />
      <MeshCollider geometry={nodes.Cube025.geometry} material={materials.Material} position={[32.5, 2.5, 1]} />
      <MeshCollider geometry={nodes.Cube026.geometry} material={materials.Material} position={[31, 5.5, 1]} />
      <MeshCollider geometry={nodes.Cube027.geometry} material={materials.Material} position={[35, 2.5, 1]} />
      <MeshCollider geometry={nodes.Cube028.geometry} material={materials.Material} position={[35, 5.5, 1]} />
      <MeshCollider geometry={nodes.Cube029.geometry} material={materials.Material} position={[-35, -2.5, 1]} />
      <MeshCollider geometry={nodes.Cube030.geometry} material={materials.Material} position={[-35, -5.5, 1]} />
      <MeshCollider geometry={nodes.Cube031.geometry} material={materials.Material} position={[-31, -5.5, 1]} />
      <MeshCollider geometry={nodes.Cube032.geometry} material={materials.Material} position={[-32.5, -2.5, 1]} />
      <MeshCollider geometry={nodes.Cube033.geometry} material={materials.Material} position={[-29.5, -4, 1]} />
      <MeshCollider geometry={nodes.Cube034.geometry} material={materials.Material} position={[-32.5, 0, 1]} />
      <MeshCollider geometry={nodes.Cube035.geometry} material={materials.Material} position={[-29.5, -1.5, 1]} />
      <MeshCollider geometry={nodes.Cube036.geometry} material={materials.Material} position={[-31, 1.5, 1]} />
      <MeshCollider geometry={nodes.Cube037.geometry} material={materials.Material} position={[-27, -1.5, 1]} />
      <MeshCollider geometry={nodes.Cube038.geometry} material={materials.Material} position={[-27, 1.5, 1]} />
      <MeshCollider geometry={nodes.Cube039.geometry} material={materials.Material} position={[13.66, 7.29, 1]} />
      <MeshCollider geometry={nodes.Cube040.geometry} material={materials.Material} position={[4.66, -14.71, 1]} />
      <MeshCollider geometry={nodes.Cube041.geometry} material={materials.Material} position={[13.66, -7.71, 1]} />
      <MeshCollider geometry={nodes.Cube042.geometry} material={materials.Material} position={[-15.34, 5.29, 1]} />
      <MeshCollider geometry={nodes.Cube043.geometry} material={materials.Material} position={[-7.34, 13.29, 1]} />
      <MeshCollider geometry={nodes.Cube044.geometry} material={materials.Material} position={[-13.34, -5.71, 1]} />
      <MeshCollider geometry={nodes.Cube045.geometry} material={materials.Material} position={[-9.34, -16.71, 1]} />
      <MeshCollider geometry={nodes.Cube046.geometry} material={materials.Material} position={[-21.34, -11.71, 1]} />
      <MeshCollider geometry={nodes.Cube047.geometry} material={materials.Material} position={[-19.34, 15.29, 1]} />
      <MeshCollider geometry={nodes.Cube048.geometry} material={materials.Material} position={[14.66, 15.29, 1]} />
      <MeshCollider geometry={nodes.Cube049.geometry} material={materials.Material} position={[22.66, -15.71, 1]} />
      <MeshCollider geometry={nodes.Cube050.geometry} material={materials.Material} position={[-14.5, 13, 1]} />
      <MeshCollider geometry={nodes.Cube051.geometry} material={materials.Material} position={[-13, 14.5, 1]} />
      <MeshCollider geometry={nodes.Cube052.geometry} material={materials.Material} position={[15, -18.5, 1]} />
      <MeshCollider geometry={nodes.Cube053.geometry} material={materials.Material} position={[16.5, -17, 1]} />
      <MeshCollider geometry={nodes.Cube054.geometry} material={materials.Material} position={[22.5, 11, 1]} />
      <MeshCollider geometry={nodes.Cube055.geometry} material={materials.Material} position={[21, 12.5, 1]} />
      <MeshCollider geometry={nodes.Cube056.geometry} material={materials.Material} position={[-17.5, -13, 1]} />
      <MeshCollider geometry={nodes.Cube057.geometry} material={materials.Material} position={[-16, -14.5, 1]} />
      <MeshCollider geometry={nodes.Cube058.geometry} material={materials.Material} position={[-19.34, 1.29, 1]} />
      <MeshCollider geometry={nodes.Cube063.geometry} material={materials.Material} position={[36.5, 14.8, 1]} />
      <MeshCollider geometry={nodes.Cube064.geometry} material={materials.Material} position={[36.5, -7, 1]} />
      <MeshCollider geometry={nodes.Cube079.geometry} material={materials.Material} position={[-1, 19.5, 1]} />
      <MeshCollider geometry={nodes.Cube092.geometry} material={materials.Material} position={[0, -21.5, 1]} />
      <MeshCollider geometry={nodes.Cube106.geometry} material={materials.Material} position={[26, 2.5, 2]} />
      <MeshCollider geometry={nodes.Cube107.geometry} material={materials.Material} position={[0, 18.5, 2]} />
      <MeshCollider geometry={nodes.Cube108.geometry} material={materials.Material} position={[-26, -2.5, 2]} />
      <MeshCollider geometry={nodes.Cube109.geometry} material={materials.Material} position={[0, -20.5, 2]} />
      <MeshCollider geometry={nodes.Cube059.geometry} material={materials.Material} position={[-36.5, 7.8, 1]} />
      <MeshCollider geometry={nodes.Cube060.geometry} material={materials.Material} position={[25.5, -19, 1]} />
      <MeshCollider geometry={nodes.Cube061.geometry} material={materials.Material} position={[27, -17.5, 1]} />
      <MeshCollider geometry={nodes.Cube062.geometry} material={materials.Material} position={[28.5, -15, 1]} />
      <MeshCollider geometry={nodes.Cube065.geometry} material={materials.Material} position={[30, -13.5, 1]} />
      <MeshCollider geometry={nodes.Cube066.geometry} material={materials.Material} position={[32.5, -11, 1]} />
      <MeshCollider geometry={nodes.Cube067.geometry} material={materials.Material} position={[34, -9.5, 1]} />
      <MeshCollider geometry={nodes.Cube068.geometry} material={materials.Material} position={[-36.5, -15, 1]} />
      <MeshCollider geometry={nodes.Cube069.geometry} material={materials.Material} position={[-25.5, -19, 1]} />
      <MeshCollider geometry={nodes.Cube070.geometry} material={materials.Material} position={[-27, -17.5, 1]} />
      <MeshCollider geometry={nodes.Cube071.geometry} material={materials.Material} position={[-29.5, -15, 1]} />
      <MeshCollider geometry={nodes.Cube072.geometry} material={materials.Material} position={[-31, -13.5, 1]} />
      <MeshCollider geometry={nodes.Cube073.geometry} material={materials.Material} position={[-33.5, -11, 1]} />
      <MeshCollider geometry={nodes.Cube074.geometry} material={materials.Material} position={[-35, -9.5, 1]} />
      <MeshCollider geometry={nodes.Cube075.geometry} material={materials.Material} position={[-28, 16.5, 1]} />
      <MeshCollider geometry={nodes.Cube076.geometry} material={materials.Material} position={[-26.5, 18, 1]} />
      <MeshCollider geometry={nodes.Cube077.geometry} material={materials.Material} position={[-32, 12.5, 1]} />
      <MeshCollider geometry={nodes.Cube078.geometry} material={materials.Material} position={[-30.5, 14, 1]} />
      <MeshCollider geometry={nodes.Cube080.geometry} material={materials.Material} position={[-35, 8.5, 1]} />
      <MeshCollider geometry={nodes.Cube081.geometry} material={materials.Material} position={[-33.5, 10, 1]} />
      <MeshCollider geometry={nodes.Cube084.geometry} material={materials.Material} position={[26.5, 18, 1]} />
      <MeshCollider geometry={nodes.Cube085.geometry} material={materials.Material} position={[28, 16.5, 1]} />
      <MeshCollider geometry={nodes.Cube086.geometry} material={materials.Material} position={[29.5, 15, 1]} />
      <MeshCollider geometry={nodes.Cube087.geometry} material={materials.Material} position={[31, 13.5, 1]} />
      <MeshCollider geometry={nodes.Cube088.geometry} material={materials.Material} position={[32.5, 12, 1]} />
      <MeshCollider geometry={nodes.Cube089.geometry} material={materials.Material} position={[34, 10.5, 1]} />
      <MeshCollider geometry={nodes.Cube082.geometry} material={materials.Material} position={[25, 19.5, 1]} />
      <MeshCollider geometry={nodes.Cube083.geometry} material={materials.Material} position={[-26, 2.5, 2]} />
      <MeshCollider geometry={nodes.Cube090.geometry} material={materials.Material} position={[26, -2.5, 2]} />
    </group>
  )
}

useGLTF.preload('models/flower-room.glb')
