/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: any,
  materials: {
    green: THREE.MeshStandardMaterial
    orange: THREE.MeshStandardMaterial
    yellow: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('models/flowers.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[5.69, -0.4, 3.95]}>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(1)'].geometry} material={materials.green} castShadow receiveShadow/>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(1)_1'].geometry} material={materials.orange} castShadow receiveShadow/>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(1)_2'].geometry} material={materials.yellow} castShadow receiveShadow/>
      </group>
      <group position={[-2.28, 2.23, 7.03]}>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(10)'].geometry} material={materials.green} castShadow receiveShadow/>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(10)_1'].geometry} material={materials.orange} castShadow receiveShadow/>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(10)_2'].geometry} material={materials.yellow} castShadow receiveShadow/>
      </group>
      <group position={[0.09, -2.52, 7.93]}>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(11)'].geometry} material={materials.green} castShadow receiveShadow/>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(11)_1'].geometry} material={materials.orange} castShadow receiveShadow/>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(11)_2'].geometry} material={materials.yellow} castShadow receiveShadow/>
      </group>
      <group position={[-2.55, -0.54, 10.15]}>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(12)'].geometry} material={materials.green} castShadow receiveShadow/>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(12)_1'].geometry} material={materials.orange} castShadow receiveShadow/>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(12)_2'].geometry} material={materials.yellow} castShadow receiveShadow/>
      </group>
      <group position={[-4.42, -3.75, 10.01]}>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(13)'].geometry} material={materials.green} castShadow receiveShadow/>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(13)_1'].geometry} material={materials.orange} castShadow receiveShadow/>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(13)_2'].geometry} material={materials.yellow} castShadow receiveShadow/>
      </group>
      <group position={[4.11, -2.79, 10.65]}>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(14)'].geometry} material={materials.green} castShadow receiveShadow/>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(14)_1'].geometry} material={materials.orange} castShadow receiveShadow/>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(14)_2'].geometry} material={materials.yellow} castShadow receiveShadow/>
      </group>
      <group position={[0.94, 1.36, 4.88]}>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(2)'].geometry} material={materials.green} castShadow receiveShadow/>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(2)_1'].geometry} material={materials.orange} castShadow receiveShadow/>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(2)_2'].geometry} material={materials.yellow} castShadow receiveShadow/>
      </group>
      <group position={[2.99, 2.56, 3.38]}>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(3)'].geometry} material={materials.green} castShadow receiveShadow/>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(3)_1'].geometry} material={materials.orange} castShadow receiveShadow/>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(3)_2'].geometry} material={materials.yellow} castShadow receiveShadow/>
      </group>
      <group position={[-2.16, -0.28, 3.38]}>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(4)'].geometry} material={materials.green} castShadow receiveShadow/>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(4)_1'].geometry} material={materials.orange} castShadow receiveShadow/>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(4)_2'].geometry} material={materials.yellow} castShadow receiveShadow/>
      </group>
      <group position={[0.9, 0.62, 2]}>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(5)'].geometry} material={materials.green} castShadow receiveShadow/>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(5)_1'].geometry} material={materials.orange} castShadow receiveShadow/>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(5)_2'].geometry} material={materials.yellow} castShadow receiveShadow/>
      </group>
      <group position={[0.9, -3.7, 3.02]}>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(6)'].geometry} material={materials.green} castShadow receiveShadow/>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(6)_1'].geometry} material={materials.orange} castShadow receiveShadow/>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(6)_2'].geometry} material={materials.yellow} castShadow receiveShadow/>
      </group>
      <group position={[4.04, -3.68, 5.79]}>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(7)'].geometry} material={materials.green} castShadow receiveShadow/>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(7)_1'].geometry} material={materials.orange} castShadow receiveShadow/>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(7)_2'].geometry} material={materials.yellow} castShadow receiveShadow/>
      </group>
      <group position={[-6.67, -2.02, 5.53]}>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(9)'].geometry} material={materials.green} castShadow receiveShadow/>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(9)_1'].geometry} material={materials.orange} castShadow receiveShadow/>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_(9)_2'].geometry} material={materials.yellow} castShadow receiveShadow/>
      </group>
      <group position={[3.24, 0.29, 7.17]}>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula'].geometry} material={materials.green} castShadow receiveShadow/>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_1'].geometry} material={materials.orange} castShadow receiveShadow/>
        <mesh geometry={nodes['mesh_calendula-flower_12698calendula_2'].geometry} material={materials.yellow} castShadow receiveShadow/>
      </group>
    </group>
  )
}

useGLTF.preload('models/flowers.glb')
